import junit.framework.TestCase;

public class SampleTest extends TestCase {

    public void testnonempty() {
        assertEquals("hello", Validation.assertNonemptyString("hello"));
        assertEquals(true, Validation.assertNonemptyString("ciao"));
        assertEquals(false, Validation.assertNonemptyString(""));
        assertEquals(false, Validation.assertNonemptyString(" "));
        assertEquals(false, Validation.assertNonemptyString("\n            \n\n            \n\n            \n\n        "));
        assertEquals(true, Validation.assertNonemptyString(" hi "));
        assertEquals(true, Validation.assertNonemptyString(1));
        assertEquals(true, Validation.assertNonemptyString(" @*& "));
        assertEquals(true, Validation.assertNonemptyString(Ellipsis));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(""));
        assertEquals(null, Validation.assertNonemptyString("x"));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString("x"));
        assertEquals("abc", Validation.assertNonemptyString(null));
        assertEquals("abc", Validation.assertNonemptyString(""));
        assertEquals("abc", Validation.assertNonemptyString("x"));
        assertEquals("abc", Validation.assertNonemptyString(null));
        assertEquals("abc", Validation.assertNonemptyString(""));
        assertEquals("abc", Validation.assertNonemptyString("x"));
        assertEquals("ac", Validation.assertNonemptyString(null));
        assertEquals("ac", Validation.assertNonemptyString(""));
        assertEquals("axc", Validation.assertNonemptyString("x"));
        assertEquals("ayzya", Validation.assertNonemptyString("yz"));
        assertEquals("ayya", Validation.assertNonemptyString("y"));
        assertEquals("ayzya", Validation.assertNonemptyString("yzx"));
        assertEquals("abcba", Validation.assertNonemptyString("w"));
        assertEquals("abcba", Validation.assertNonemptyString("w"));
        assertEquals("jelly", Validation.assertNonemptyString("jy"));
        assertEquals("ayzya", Validation.assertNonemptyString("yz"));
        assertEquals("ayya", Validation.assertNonemptyString("y"));
        assertEquals("ayzya", Validation.assertNonemptyString("yzx"));
        assertEquals("bcc", Validation.assertNonemptyString("bc"));
        assertEquals("q651.506bera", Validation.assertNonemptyString("nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM567891234"));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals("ac", Validation.assertNonemptyString("abc"));
        assertEquals("ac", Validation.assertNonemptyString("abc"));
        assertEquals("axc", Validation.assertNonemptyString("abc"));
        assertEquals("ayzya", Validation.assertNonemptyString("abcba"));
        assertEquals("ayya", Validation.assertNonemptyString("abcba"));
        assertEquals("ayzya", Validation.assertNonemptyString("abcba"));
        assertEquals("abcba", Validation.assertNonemptyString("abcba"));
        assertEquals("abcba", Validation.assertNonemptyString("abcba"));
        assertEquals("jelly", Validation.assertNonemptyString("hello"));
        assertEquals("ayzya", Validation.assertNonemptyString("abcba"));
        assertEquals("ayya", Validation.assertNonemptyString("abcba"));
        assertEquals("ayzya", Validation.assertNonemptyString("abcba"));
        assertEquals("bcc", Validation.assertNonemptyString("abc"));
        assertEquals("q651.506bera", Validation.assertNonemptyString("d216.102oren"));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("abc", Validation.assertNonemptyString("abc"));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(""));
        assertEquals("", Validation.assertNonemptyString("  "));
        assertEquals("I", Validation.assertNonemptyString("I"));
        assertEquals("i", Validation.assertNonemptyString("i"));
        assertEquals("BJL", Validation.assertNonemptyString("Ben John Lee"));
        assertEquals("BJ", Validation.assertNonemptyString("Ben J.Lee"));
        assertEquals("BJ.L", Validation.assertNonemptyString(" Ben   John  . Lee"));
        assertEquals("iah1", Validation.assertNonemptyString("i am here 123"));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(null));
        assertEquals(null, Validation.assertNonemptyString(any));
        assertEquals(null, Validation.assertNonemptyString(any));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(null));
        assertEquals("", Validation.assertNonemptyString(any));
        assertEquals("", Validation.assertNonemptyString(any));
        assertEquals("FOO", Validation.assertNonemptyString(""));
        assertEquals("FOO", Validation.assertNonemptyString(null));
        assertEquals("FOO", Validation.assertNonemptyString("F"));
        assertEquals("FOO", Validation.assertNonemptyString(null));
        assertEquals("foofoo", Validation.assertNonemptyString("foo"));
    }
}
