import junit.framework.TestCase;

public class WordUtilsTest extends TestCase {

    public void testwrap() {
        assertEquals("Here is one line of\ntext that is going\nto be wrapped after\n20 columns.", WordUtils.wrap("Here is one line of text that is going to be wrapped after 20 columns.", 20, "\n", false, "\n"));
        assertEquals(null, WordUtils.wrap(null, 20, "\n", false, "\n"));
        assertEquals(null, WordUtils.wrap(null, -1, "\n", false, "\n"));
        assertEquals("", WordUtils.wrap("", 20, "\n", false, "\n"));
        assertEquals("", WordUtils.wrap("", -1, "\n", false, "\n"));
        assertEquals("Here is one line of\ntext that is going\nto be wrapped after\n20 columns.", WordUtils.wrap("Here is one line of text that is going to be wrapped after 20 columns.", 20, "\n", false, "\n"));
        assertEquals("Click here to jump\nto the commons\nwebsite -\nhttp://commons.apache.org", WordUtils.wrap("Click here to jump to the commons website - http://commons.apache.org", 20, "\n", false, "\n"));
        assertEquals("Click here,\nhttp://commons.apache.org,\nto jump to the\ncommons website", WordUtils.wrap("Click here, http://commons.apache.org, to jump to the commons website", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "     This paragraph will be filled,", "first without any indentation, and then", "with some (including a hanging indent)." }, WordUtils.wrap("This paragraph will be filled, first without any indentation,\nand then with some (including a hanging indent).", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "----------", "               h", "               e", "               l", "               l", "               o" }, WordUtils.wrap("----------hello", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "    Hello there,", "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Good grief", "Python*****" }, WordUtils.wrap("Good grief Python features are advancing quickly!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day? [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello", "[...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!          ", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba daba-", "doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba", "daba-doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a", "    ", "sentence ", "with     ", "much white", "space." }, WordUtils.wrap(" This is a    sentence with     much whitespace.", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "   " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "     " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 50, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with", "leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "  abcd", "  efgh" }, WordUtils.wrap("abcd efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "    ", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be", "written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written", "-- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 36, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 15, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 17, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 19, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 31, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 35, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "A short line.  Note the single space." }, WordUtils.wrap("A short line. Note the single space.", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "Well, Doctor?  What do you think?" }, WordUtils.wrap("Well, Doctor? What do you think?", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "Well, Doctor?  What do you think?" }, WordUtils.wrap("Well, Doctor? What do you think?", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "File stdio.h is nice." }, WordUtils.wrap("File stdio.h is nice.", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-reformatting-", "posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "this-", "is-", "a-", "useful-", "feature-", "for-", "reformatting-", "posts-", "from-", "tim-", "peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on", "1994-01-26.  Python 1.0.1 was", "released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on 1994-01-26.", "Python 1.0.1 was released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "Python", "1.0.0", "was", "released", "on", "1994-01-26.", "Python", "1.0.1", "was", "released", "on", "1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 27, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at 7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "I", "do", "all", "my", "shopping", "at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with non-", "breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with", "non-breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "Die", "Empfänger-", "Auswahl" }, WordUtils.wrap("Die Empfänger-Auswahl", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?", "I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "aa ää-", "ää" }, WordUtils.wrap("aa ää-ää", 7, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the", "-n option, or --dry-", "run in its long", "form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n", "option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 21, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 34, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 38, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 39, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a paragraph that already has line", "breaks.  But some of its lines are much", "longer than the others, so it needs to be", "wrapped.  Some lines are  tabbed too.  What a", "mess!" }, WordUtils.wrap("This is a paragraph that already has\nline breaks.  But some of its lines are much longer than the others,\nso it needs to be wrapped.\nSome lines are \ttabbed too.\nWhat a mess!\n", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "        Test    default         tabsize." }, WordUtils.wrap("\tTest\tdefault\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "    Test    custom      tabsize." }, WordUtils.wrap("\tTest\tcustom\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short", "paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "(1) This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "     This paragraph will be filled,", "first without any indentation, and then", "with some (including a hanging indent)." }, WordUtils.wrap("This paragraph will be filled, first without any indentation,\nand then with some (including a hanging indent).", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "----------", "               h", "               e", "               l", "               l", "               o" }, WordUtils.wrap("----------hello", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "    Hello there,", "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Good grief", "Python*****" }, WordUtils.wrap("Good grief Python features are advancing quickly!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day? [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello", "[...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!          ", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba daba-", "doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba", "daba-doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a", "    ", "sentence ", "with     ", "much white", "space." }, WordUtils.wrap(" This is a    sentence with     much whitespace.", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "   " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "     " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 50, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with", "leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "  abcd", "  efgh" }, WordUtils.wrap("abcd efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "    ", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be", "written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written", "-- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 36, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 15, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 17, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 19, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 31, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 35, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "A short line.  Note the single space." }, WordUtils.wrap("A short line. Note the single space.", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "Well, Doctor?  What do you think?" }, WordUtils.wrap("Well, Doctor? What do you think?", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "Well, Doctor?  What do you think?" }, WordUtils.wrap("Well, Doctor? What do you think?", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "File stdio.h is nice." }, WordUtils.wrap("File stdio.h is nice.", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-reformatting-", "posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "this-", "is-", "a-", "useful-", "feature-", "for-", "reformatting-", "posts-", "from-", "tim-", "peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on", "1994-01-26.  Python 1.0.1 was", "released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on 1994-01-26.", "Python 1.0.1 was released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "Python", "1.0.0", "was", "released", "on", "1994-01-26.", "Python", "1.0.1", "was", "released", "on", "1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 27, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at 7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "I", "do", "all", "my", "shopping", "at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with non-", "breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with", "non-breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "Die", "Empfänger-", "Auswahl" }, WordUtils.wrap("Die Empfänger-Auswahl", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?", "I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "aa ää-", "ää" }, WordUtils.wrap("aa ää-ää", 7, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the", "-n option, or --dry-", "run in its long", "form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n", "option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 21, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 34, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 38, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 39, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a paragraph that already has line", "breaks.  But some of its lines are much", "longer than the others, so it needs to be", "wrapped.  Some lines are  tabbed too.  What a", "mess!" }, WordUtils.wrap("This is a paragraph that already has\nline breaks.  But some of its lines are much longer than the others,\nso it needs to be wrapped.\nSome lines are \ttabbed too.\nWhat a mess!\n", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "        Test    default         tabsize." }, WordUtils.wrap("\tTest\tdefault\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "    Test    custom      tabsize." }, WordUtils.wrap("\tTest\tcustom\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short", "paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "(1) This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
        assertEquals("This paragraph will be filled, first\nwithout any indentation, and then with\nsome (including a hanging indent).", WordUtils.wrap("This paragraph will be filled, first without any indentation,\nand then with some (including a hanging indent).", 40, "\n", false, "\n"));
        assertEquals("     This paragraph will be filled,\nfirst without any indentation, and then\nwith some (including a hanging indent).", WordUtils.wrap("This paragraph will be filled, first without any indentation,\nand then with some (including a hanging indent).", 40, "\n", false, "\n"));
        assertEquals("  * This paragraph will be filled, first\n    without any indentation, and then\n    with some (including a hanging\n    indent).", WordUtils.wrap("This paragraph will be filled, first without any indentation,\nand then with some (including a hanging indent).", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "----------", "               h", "               e", "               l", "               l", "               o" }, WordUtils.wrap("----------hello", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "    Hello there,", "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "  [truncated]..." }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Good grief", "Python*****" }, WordUtils.wrap("Good grief Python features are advancing quickly!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day? [...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello", "[...]" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!          ", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba daba-", "doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "yaba", "daba-doo" }, WordUtils.wrap("yaba daba-doo", 10, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a", "    ", "sentence ", "with     ", "much white", "space." }, WordUtils.wrap(" This is a    sentence with     much whitespace.", 10, "\n", false, "\n"));
        assertEquals(new Object[] { "   " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "     " }, WordUtils.wrap("   ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 50, "\n", false, "\n"));
        assertEquals(new Object[] { " This is a sentence with", "leading whitespace." }, WordUtils.wrap(" This is a sentence with leading whitespace.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "  abcd", "  efgh" }, WordUtils.wrap("abcd efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "    ", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "abcd", "efgh" }, WordUtils.wrap("abcd    efgh", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("  ", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be", "written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written", "-- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written --", "thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "Em-dashes should be written -- thus." }, WordUtils.wrap("Em-dashes should be written -- thus.", 36, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 15, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do", "--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 16, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 17, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--", "this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 19, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even", "---this." }, WordUtils.wrap("You can also do--this or even---this.", 31, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You can also do--this or even---", "this." }, WordUtils.wrap("You can also do--this or even---this.", 35, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] {}, WordUtils.wrap("", 6, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-", "reformatting-posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "this-is-a-useful-feature-for-reformatting-", "posts-from-tim-peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "this-", "is-", "a-", "useful-", "feature-", "for-", "reformatting-", "posts-", "from-", "tim-", "peters'ly" }, WordUtils.wrap("this-is-a-useful-feature-for-reformatting-posts-from-tim-peters'ly", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on", "1994-01-26.  Python 1.0.1 was", "released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "Python 1.0.0 was released on 1994-01-26.", "Python 1.0.1 was released on 1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "Python", "1.0.0", "was", "released", "on", "1994-01-26.", "Python", "1.0.1", "was", "released", "on", "1994-02-15." }, WordUtils.wrap("Python 1.0.0 was released on 1994-01-26.  Python 1.0.1 was\nreleased on 1994-02-15.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 25, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 27, "\n", false, "\n"));
        assertEquals(new Object[] { "I do all my shopping at 7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 29, "\n", false, "\n"));
        assertEquals(new Object[] { "I", "do", "all", "my", "shopping", "at", "7-11." }, WordUtils.wrap("I do all my shopping at 7-11.", 1, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with non-", "breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a sentence", "with", "non-breaking\u202fspace." }, WordUtils.wrap("This is a sentence with non-breaking�?�space.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "Die", "Empfänger-", "Auswahl" }, WordUtils.wrap("Die Empfänger-Auswahl", 13, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there,", "how are you", "this fine", "day?  I'm", "glad to hear", "it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 12, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?", "I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 42, "\n", false, "\n"));
        assertEquals(new Object[] { "Hello there, how are you this fine day?  I'm glad to hear it!" }, WordUtils.wrap("Hello there, how are you this fine day?  I'm glad to hear it!", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "aa ää-", "ää" }, WordUtils.wrap("aa ää-ää", 7, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the", "-n option, or --dry-", "run in its long", "form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n", "option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 21, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 32, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 34, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 35, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or", "--dry-run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 38, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 39, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-", "run in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 41, "\n", false, "\n"));
        assertEquals(new Object[] { "You should use the -n option, or --dry-run", "in its long form." }, WordUtils.wrap("You should use the -n option, or --dry-run in its long form.", 42, "\n", false, "\n"));
        assertEquals("This is a paragraph that already has line\nbreaks.  But some of its lines are much\nlonger than the others, so it needs to be\nwrapped.  Some lines are  tabbed too.  What a\nmess!", WordUtils.wrap("This is a paragraph that already has\nline breaks.  But some of its lines are much longer than the others,\nso it needs to be wrapped.\nSome lines are \ttabbed too.\nWhat a mess!\n", 70, "\n", false, "\n"));
        assertEquals(new Object[] { "        Test    default         tabsize." }, WordUtils.wrap("\tTest\tdefault\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "    Test    custom      tabsize." }, WordUtils.wrap("\tTest\tcustom\t\ttabsize.", 80, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short", "paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 20, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short paragraph." }, WordUtils.wrap("This is a\nshort paragraph.", 40, "\n", false, "\n"));
        assertEquals(new Object[] { "This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
        assertEquals(new Object[] { "(1) This is a short line." }, WordUtils.wrap("This is a short line.", 30, "\n", false, "\n"));
    }
}